apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repos.yaml
  - cert-manager.yaml
  - cert-manager-issuer.yaml
  - metallb.yaml
  - metallb-pool.yaml
  - ingress-nginx.yaml
  - monitoring.yaml
  - additional-scrape-configs.yaml
  - minio.yaml
  - nvidia-gpu.yaml
  - node-feature-discovery.yaml
  - registry.yaml
